### ISSUE TITLE
Start of project

### ISSUE THREAD

**Issue by joon0017** [JJangJo/miniproject#1]
프로젝트 주제: 빵 판매/주문 관리 시스템
    ㄴ> 에인트에서 직접 값을 계산하는 것이 아니라 메뉴 명을 골라서 구매 가능 하게

프로젝트 인원:
owner: 장세창
member: 조성준

**Comment by newwin01** [comment]
OSS: 팀 프로젝트
- 빵 주문 자동화 시스템
왜 필요한가? 
- https://www.fnnews.com/news/202204260836079074: 신세계푸드 베이커리 배달서비스 '새벽빵' 인기: 
이 같은 판매량 증가는 코로나19 장기화와 서구화된 식습관으로 인해 빵을 간식이나 디저트가 아니라 밥 대신 주식으로 즐기며 신선한 빵을 찾는 소비자가 늘었기 때문으로 신세계푸드 측은 분석했다. 이와 함께 집에서도 빵을 커피, 음료와 함께 곁들여 먹는 홈카페, 홈디저트 문화가 확산되며 빵의 신선함을 중시하는 트렌드도 새벽빵 판매 증가의 원인 중 하나로 꼽았다.
-> 한국인의 식습관 서구화로 인한 빵에 대한 수요 증가. 
-> 코로나로 인한 인건비 부담 증가
-> 빵은 제작 후 빨리 상하기 때문에 만든 빵은 당일에 판매되는 것이 이득
-> 재고 관리 및 데이터 모집이 필수
-> 다양한 빵 종류에 대해 사람들이 자신의 알러지에 대하여 알지 못할 가능성(정보 제공 필요)

**Comment by newwin01** [comment]
빵 판매/주문 관리 시스템 누구를 aim 해야 할 것인가? 
User를 목적으로 할 것인가 아니면, 빵집 주인을 위한 프로그램인가?

**Comment by joon0017** [comment]
aim: 
빵 판매 목적은 소비자 및 관리자 동일하게 이득을 볼 수가 있다. 
소비자: 간편한 사용이 가능함
주인: 판매 데이터 등 다양한 정보를 수집 할 수 있음.
서로 이득을 보는 시스템이다.
