### ISSUE TITLE
함수 구현

### ISSUE THREAD

**Issue by newwin01** [JJangJo/miniproject#2]
어떠한 함수가 필요할 것인가?

**Comment by joon0017** [comment]
구조체: 제품명, 가격, 잔고

**Comment by newwin01** [comment]
가능한 그 외 기능:
-> 검색 기능
-> 총 가격 계산
-> 회원이라면 할인된 가격 계산
-> 파일 읽기,저장
-> 자동 품절 처리

**Comment by joon0017** [comment]
기본적인 CRUD 기능들 (추가, 조회, 수정, 제거)

**Comment by joon0017** [comment]
> 구조체: 제품명, 가격, 잔고

추가: 총 판매량
char name[20];
int price;
int remain;
int totalSales;

**Comment by joon0017** [comment]
사용할 함수들 (parameter는 일단 보류):
search(); -> 이름을 사용하여 검색하는 기능. 검색 하는 것이 존재 하면 그 재품의 구매 페이지로 이동
showMenu(); -> 기본 메뉴 출력 하는 기능. (선택지 재공)

addCart(); -> 장바구니에 추가 하는 기능
showCart(); -> 장바구니 조회

saveFile(); 현재 리스트 저장 기능 (장바구니는 따로 저장 안함). 메뉴만 저장 하도록
readFile(); 저장되어 있는 파일을 불러오는 기능

-------------------------------------------------------------------------------------
그 외 기본적인 crud 기능들
add()
read()
update()
delete()

**Comment by joon0017** [comment]
처음 프로그램을 실행 했을 경우, 관리자(빵집 주인)인지 사용자(손님)인지 선택 가능
관리자: 메뉴 수정, 업데이트 등
사용자: 메뉴를 읽을 수 있고, 장바구니 추가, 계산 등 가능

**Comment by newwin01** [comment]
회원이라면 할인 되는 시스템 구현을 위해서는 어떠한 방식을 사용하면 좋을 것인가?
회원 할인의 필요성?

**Comment by joon0017** [comment]
회원 경우에는 결제 하는 단계에서 "회원입니까?" 를 질문 후
예-> 회원 할인 적용 (총 가격의 몇% 차감)
아니요 -> 그냥 결제

checkMember(); ->회원인지 아닌지 확인. return 값: 1=회원임/0=회원아님
totalSum(); -> 장바구니 총 가격 계산 함수

if (checkMember()==1) printf("총 가격은 %f 입니다",(totalSum()*할인값));
else /*~그냥 출력*/

**Comment by joon0017** [comment]
struct:

typedef struct
{
	char name[20];
	char info[50];
        int price;
        int remain;
        int totalSales;
}product;

**Comment by newwin01** [comment]
포인터 함수 사용? 함수 사용? 
-> 포인터 함수 사용 결정

**Comment by joon0017** [comment]
장바구니 관련:
장바구니는 그냥 새로운 list를 만들면 되기 때문에,
관리자가 사용하는 함수(crud)를 재사용 하면 됨
